### ISSUE TITLE
\w not working after installation (using pathogen)

### ISSUE THREAD

**Issue by faxotherapy** [easymotion/vim-easymotion#147]
Hello, easymotion seems installed properly since I have access to the help file via “:help”. Problem is when I press the character \, the latter is not recognised. So, following \ by letter w has no effect. Thank you.

**Comment by JeffreyWay** [comment]
I'm going to be the annoying guy that comments a year and a half later. :)

I had this exact same problem. Couldn't figure out why I kept getting "EasyMotion: Invalid Target." It turns out that I had invisible spaces on the line. So something like:

```
nmap s <Plug>(easymotion-s2)_______
```

I deleted the spaces at the end of the line, and everything started working. Go figure.

Anyways, to the person who traces Google to this thread in 2016, hope it helps :)

**Comment by haya14busa** [comment]
:+1:
