### ISSUE TITLE
Visual mode weird cursor jump

### ISSUE THREAD

**Issue by WscriChy** [easymotion/vim-easymotion#210]
I have a mapping 

map w <Plug>(easymotion-w)

When I am in visual mode and press w, the cursor jumps at the first line on the screen from the current position, but everything else stays ok (like highlightin of motion region and first letters of motion words).

So the forward word motion actually works, but there is this unexpected cursor jump in visual mode.

**Comment by haya14busa** [comment]
I cannot reproduce it. What is the out put of `:verbose vmap w`?

**Comment by WscriChy** [comment]
s  w             <Plug>(easymotion-w)
x  w             <Plug>(easymotion-w)

**Comment by haya14busa** [comment]
Hm... I cannot reproduce this. Please describe more detail reproduction steps.

**Comment by roboguy13** [comment]
I have the same problem. I have installed easymotion with pathogen, with no changes to my vimrc. If I go to the (say) the middle of a file and type this in normal mode: `v<space><space>w`, the cursor jumps to the first line of the file.

It looks like this is purely a graphical bug, since it seems to select the correct text when I finish out the command (at least, in the cases I tried), but it is annoying since it makes it impossible to visually see where you're starting your selection from.

**Comment by WscriChy** [comment]
>I don't know if this is relevant at all, but my leader key is space.
I think it is somehow relevant because I have also space leader.

**Comment by WscriChy** [comment]
Fixed it by saving the view  at the beginning of `s:EasyMotion` function

            let win_saved_view = winsaveview()

And then restore it in the same function by

            keepjumps call winrestview(win_saved_view)

Instead of 

            keepjumps call winrestview({'lnum' : win_first_line, 'topline' : win_first_line})

**Comment by haya14busa** [comment]
Sorry for the late reply. I fixed it.
