### ISSUE TITLE
Moving repo into organization?

### ISSUE THREAD

**Issue by mattn** [easymotion/vim-easymotion#231]
@Lokaltog as far as i can see, you seems not actively about vim-easymotion in long time. However haya12busa works on very well. It's not very constructive, it's strange development model. I think you've better to transform this into organization repository. Or transform to haya14busa?
How do you think?

**Comment by haya14busa** [comment]
@mattn @Lokaltog 

Thanks for the comment @mattn
I'm fine with current development style, so it's not necessary to make this repo into organization repository.
However, it's true that I sometimes feel it's inconvenient because of the permission I have.
For example, I cannot open `Wiki` feature, github pages, and modify the description of the repository(I guess there are no need to moidfy though).
So, @Lokaltog, If you are ok to make it organization repository, I think it's better to do that because it sometimes helps me or broaden the actibity on easymotion.

**Comment by Lokaltog** [comment]
Sounds good to me! If you create an easymotion organization and give me admin access I'll transfer the repo. :)

**Comment by haya14busa** [comment]
@Lokaltog Thanks! :sparkles:
I just created organization (https://github.com/easymotion ) and invite you as a owner.

**Comment by haya14busa** [comment]
I confirmed the transfer of the repository to the organization. Thanks again for your work @Lokaltog and @mattn for the suggestion :+1:
