### ISSUE TITLE
Not highlighted if executed `:highlight clear`

### ISSUE THREAD

**Issue by Shougo** [easymotion/vim-easymotion#272]
Minimal .vimrc

```vim
set nocompatible
set runtimepath+=~/.cache/neobundle/vim-easymotion/

nmap w <Plug>(easymotion-lineforward)

call setline(1, 'foobar foobaz')
```

Reproduce ways:

OK version

* `:highlight clear`

* `w`

* Highlighted

NG version

* `w`

* `:highlight clear`

* Not highlighted

Related issue:

#143, #203

**Comment by haya14busa** [comment]
I confirmed it. I can reproduce it.
But I'm not sure it's an unexpected behavior or not.
If the user executes `:highlight clear`, of course highlight defined by EasyMotion also loose color.
It might be expected behavior.

For example, `:highlight clear` doesn't delete the highlight definition. It just clear highlight.


### Before `:hi clear`

- `:highlight EasyMotionTarget`
  - => `EasyMotionTargetDefault xxx cterm=bold ctermfg=196 gui=bold guifg=#ff0000` (expected)
- `:echo hlexists('EasyMotionTargetDefault')`
  - => 1 (expected)

### After `:hi clear`
```vim
:hi clear
```

- `:highlight EasyMotionTarget`
  - => `EasyMotionTargetDefault xxx cleared`
- `:echo hlexists('EasyMotionTargetDefault')`
  - => 1

Both results are expected. The problem is user's intention.
If they have an intention to clear the highlight and run `:hi clear`,
I'm not sure it's a correct behavior or not to re-configure the highlight of easymotion.
The user might not expect this behavior.

For the `:hi clear` in colorscheme, EasyMotion already handles it.
because `:hi clear` in colorscheme is exists for clearing old highlight.
The highlight of EasyMotion has nothing to do with colorscheme, so it makes sense to re-configure them.

If `:hi clear` is in your vimrc or your installed plugins, I think your vimrc or plugins should fix it.

**Comment by haya14busa** [comment]
If the user customize the highlight of easymotion like below, easymotion cannot respect this setting after all after `:hi clear`.

```
autocmd ColorScheme * hi EasyMotionTarget ctermbg=none ctermfg=green
```

**Comment by Shougo** [comment]
I get the problem.

nested is needed for the autocmd.

```
  " Reload .vimrc automatically.
  autocmd BufWritePost .vimrc,vimrc,*.rc.vim,neobundle*.toml nested
        \ | source $MYVIMRC | redraw
```

`:help autocmd-nested`

I close the issue.  But I think the FAQ is needed for the problem.

**Comment by haya14busa** [comment]
Thanks! I'll consider to add FAQ.
