### ISSUE TITLE
shading doesn't work with folds

### ISSUE THREAD

**Issue by nhooyr** [easymotion/vim-easymotion#274]
This is how it looks normally
<img width="1440" alt="screen shot 2016-02-04 at 11 28 48 am" src="https://cloud.githubusercontent.com/assets/10180857/12821702/7e288594-cb32-11e5-9408-6f537706fe13.png">

Here I pressed `<leader><leader>k`
<img width="1440" alt="screen shot 2016-02-04 at 11 28 31 am" src="https://cloud.githubusercontent.com/assets/10180857/12821693/72306f22-cb32-11e5-9234-fbb571b3c5b2.png">

As you can see the shading is screwed. It works fine if I do `<leader><leader>j`. Any ideas on what the problem is? I can provide additional info.

**Comment by haya14busa** [comment]
Sorry for the late reply. It has nothing to do with fold. The syntax is messed up because easymotion overwrites buffer text with ` <leader><leader>k`.
It can't be helped.

However, for latest version of Vim, easymotion doesn't need to updating buffer text, like `<Plug>(easymotion-overwin-s)`. 
The same implementation can be applied for `<Plug>(easymotion-j)` or k with little restriction but I didn't implement it yet. Please wait for a while :)

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
