### ISSUE TITLE
Easymotion breaks my undo history

### ISSUE THREAD

**Issue by Shathur** [easymotion/vim-easymotion#290]
For some time I've had the problem that my undohistory breaks spontaneously, seemingly at random. Just now I found that the reason for this is that the undolevel is set to -1. EasyMotion is the only one of my currently installed plugins that touches this setting (and it sets it to -1).

Why does EasyMotion do this? So far I haven't been able to detect any particular pattern behind the occurrences. From the code it seems to be part of some fail handling.

**Comment by haya14busa** [comment]
Hmm.... today, I also had the problem, I cannot reproduce it though. I'll look into it.

**Comment by damage220** [comment]
I have the same issue:
1. Open a file.
2. Search through easymotion.
3. Type "u" for a few times.
Tab has changed its color and I can't leave the editor - "No write since last change for buffer".

**Comment by haya14busa** [comment]
I didn't experience this problem thesedays, and I cannot reproduce this.
Please reopen if you find reproducible way.

**Comment by dimxdim** [comment]
I also experience this issue. GVim on Windows 10, both 64bit. Precompiled version from https://tuxproject.de/projects/vim/
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 22 2017 20:05:01)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-655
Compiled by hp@HP-PC
Huge version with GUI. 
```

Also tested 64-bit version v8.0.0698 from https://github.com/vim/vim-win32-installer/releases.
Bug still occurs.
Here is how to reproduce. Install the plugin and put this in _vimrc:
```
set nocompatible               " Be iMproved
set laststatus=2    " Always show status bar
map <Leader> <Plug>(easymotion-prefix)
```
Now open any file that has some text in it
`:e ~/_vimrc`
Press `<Leader>j` to highlight the beginning of each line.
Press `<Esc>` to cancel the motion (or any key to perform motion - does not matter)
Press `u` to undo.

Expected behavior: nothing happens to the buffer, since we did not change any text.

Actual behavior: `u` puts buffer in a changed state (as if some change was performed). The statusline on the bottom shows [+] as there was a modification to the buffer.
